server:
  port: 9000

#spring:
#  security:
#    oauth2:
#      authorizationserver:
#        client:
#          react-app:
#            require-authorization-consent: true
#            registration:
#              client-id: react-app
#              client-secret: "{noop}admin"
#              authorization-grant-types: client_credentials,authorization_code,refresh_token
#              redirect-uris: http://127.0.0.1:8080/login/oauth2/code/react-app
#              scopes:
#                - openid
#                - profile
#                - write
#              client-authentication-methods: client_secret_basic
